# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Skyconqueror | Heavy Metal 
email: info@skyconqueror.de 
description: >
    Skyconqueror is a straight heavy metal band founded
    in the surroundings of MÃ¼nster (North Western 
    Germany) in early 1999
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.skyconqueror.de" # the base hostname & protocol for your site
twitter_username: skyconqueror666 
github_username:  

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed
